### ISSUE TITLE
model导入问题 sequelize.import报错

### ISSUE THREAD

**Issue by yongruning** [demopark/sequelize-docs-Zh-CN#42]
const User = sequelize.import('../models/rpa_user')
在导入model的时候，报错Path must be a string. Received undefined，可是我明明用的是字符串的路径啊，有没有大佬碰到过这个问题

**Comment by yongruning** [comment]
D:\webstrom_workspace\eshore_rpa\node_modules\vue\dist\vue.runtime.common.dev.js:8412 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
D:\webstrom_workspace\eshore_rpa\node_modules\vue-router\dist\vue-router.common.js:18 [vue-router] Failed to resolve async component default: TypeError: Path must be a string. Received undefined
warn @ D:\webstrom_workspace\eshore_rpa\node_modules\vue-router\dist\vue-router.common.js:18
D:\webstrom_workspace\eshore_rpa\node_modules\vue-router\dist\vue-router.common.js:18 [vue-router] uncaught error during route navigation:
warn @ D:\webstrom_workspace\eshore_rpa\node_modules\vue-router\dist\vue-router.common.js:18
D:\webstrom_workspace\eshore_rpa\node_modules\vue-router\dist\vue-router.common.js:2119 TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.dirname (path.js:728:5)
    at Sequelize.import (D:\webstrom_workspace\eshore_rpa\node_modules\sequelize\lib\sequelize.js:475:31)
    at Module.eval (webpack-internal:///./src/renderer/db/controller/UserController.js:5:28)
    at eval (webpack-internal:///./src/renderer/db/controller/UserController.js:12:30)
    at Module../src/renderer/db/controller/UserController.js (http://localhost:9999/0.js:199:1)
    at __webpack_require__ (http://localhost:9999/renderer.js:834:30)
    at fn (http://localhost:9999/renderer.js:131:20)
    at eval (webpack-internal:///./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/index.js?!./src/renderer/components/views/login/index.vue?vue&type=script&lang=js&:3:87)
    at Module../node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/index.js?!./src/renderer/components/views/login/index.vue?vue&type=script&lang=js& (http://localhost:9999/0.js:11:1)
    at __webpack_require__ (http://localhost:9999/renderer.js:834:30)
    at fn (http://localhost:9999/renderer.js:131:20)
    at eval (webpack-internal:///./src/renderer/components/views/login/index.vue?vue&type=script&lang=js&:2:188)
    at Module../src/renderer/components/views/login/index.vue?vue&type=script&lang=js& (http://localhost:9999/0.js:115:1)
    at __webpack_require__ (http://localhost:9999/renderer.js:834:30)
    at fn (http://localhost:9999/renderer.js:131:20)
    at eval (webpack-internal:///./src/renderer/components/views/login/index.vue:3:93)
    at Module../src/renderer/components/views/login/index.vue (http://localhost:9999/0.js:103:1)
    at __webpack_require__ (http://localhost:9999/renderer.js:834:30)
    at fn (http://localhost:9999/renderer.js:131:20)
    at <anonymous>


这是报错信息

**Comment by demopark** [comment]
sequelize.import() 这里的 `sequelize` 需要是 new Sequelize() 实例

**Comment by yongruning** [comment]
@demopark 在英文文档那边看到了，是webpack整合sequelize时底层会对path进行处理，他们提供了import的代替方案，也可以使用绝对路径处理，具体没太详细的去了解，暂时用绝对路径解决了，项目比较赶
